services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    command: "npm run dev"
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - api
    command: "npm run start"