name: dc-ar
services:
  api:
    container_name: dc-ar-api
    build:
      context: ./src/backend
      dockerfile: ./df-prod.Dockerfile
    restart: always
    networks:
      - internal

  frontend:
    container_name: dc-ar-frontend
    build:
      context: ./src/frontend
      dockerfile: ./df-prod.Dockerfile
      args:
        - MOUNT_PATH=/dc/auto-refresher/
    ports:
      - 85:8080
    depends_on:
      - api
    restart: always
    networks:
      - dc
      - internal

networks:
  internal:
  dc:
    external: true