name: dc-ar
services:
  fart:
    build:
      context: .
      dockerfile: ./df-prod.Dockerfile
    ports:
      - 49120:3000
    restart: unless-stopped
    networks:
      #- dragcave
      - internal

networks:
  #dragcave:
  #external: true
  internal:
