name: dc-ar_dev
services:
  dev:
    image: node:lts
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - .:/workspace:delegated
    restart: unless-stopped
    command: sleep infinity

networks:
  internal:
