name: dc-ar_dev
services:
  dev:
    image: node:lts
    ports:
      - 3000:3000
    environment:
      - APP_VERSION=${APP_VERSION}
      - API_KEY=${API_KEY}
      - ENV CHOKIDAR_USEPOLLING=true
      - ENV NODE_ENV=development
    networks:
      - internal
    volumes:
      - .:/workspace:delegated
    restart: unless-stopped
    command: sleep infinity

networks:
  internal:
