name: dc-ar
services:
  api:
    build:
      context: ./src/backend
      dockerfile: ./df-prod.Dockerfile
    restart: unless-stopped
    networks:
      - internal

  fart:
    build:
      context: ./src/frontend
      dockerfile: ./df-prod.Dockerfile
      args:
        - APP_VERSION=${APP_VERSION}
        - MOUNT_PATH=/dc/auto-refresher/
    ports:
      - 127.0.0.1:85:${FRONTEND_PORT}
    depends_on:
      - api
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    networks:
      - dc
      - internal

networks:
  internal:
  dc:
    external: true
