services:
  api:
    container_name: dc-ar-dev-api
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - internal
    restart: unless-stopped
  frontend:
    container_name: dc-ar-dev-react
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - internal
    restart: unless-stopped

networks:
  internal: