services:
  fart:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - dragcave
      - internal

networks:
  internal:
  dragcave:
    external: true
