name: dc-ar_dev
services:
  api:
    build:
      context: ./src/backend
      dockerfile: ./df.Dockerfile
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    networks:
      - internal
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: ./df.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 5173:${VITE_PORT}
    environment:
      - VITE_APP_VERSION=${APP_VERSION}
      - VITE_PORT=${VITE_PORT}
      - API_PORT=${API_PORT}
    depends_on:
      - api
    networks:
      - internal
    restart: unless-stopped

networks:
  internal: