name: dc-ar_dev
services:
  api:
    container_name: dc-ar-dev-api
    build:
      context: ./src/backend
      dockerfile: ./df.Dockerfile
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    networks:
      - internal
    restart: unless-stopped
  frontend:
    container_name: dc-ar-dev-react
    build:
      context: ./src/frontend
      dockerfile: ./df.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - internal
    restart: unless-stopped

networks:
  internal: