FROM node:24-bookworm-slim
ENV NODE_ENV=development
ARG TESTING=false
ENV TESTING=$TESTING
WORKDIR /app

COPY --link package.json package-lock.json ./
RUN npm ci && if [ "$TESTING" = "true" ]; then npx playwright install --with-deps chromium; fi

CMD ["npm", "run", "dev"]
