name: dc-ar_dev
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: ./df.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - APP_VERSION=${APP_VERSION}
      - API_KEY=${API_KEY}
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
