services:
  api:
    build:
      context: .
      dockerfile: ./docker/prod-api.Dockerfile
    ports:
      - 3001:3001
    command: npm run prod
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - internal

  frontend:
    build:
      context: .
      dockerfile: ./docker/prod-frontend.Dockerfile
      args:
        - PUBLIC_URL=/dc/auto-refresher/
    ports:
      - 81:80
    depends_on:
      - api
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - dc
      - internal
networks:
  internal:
  dc:
    external: true